image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-gateway-microservice:
  stage: build
  script:
    gradle gateway-microservice:assemble gateway-microservice:testClasses

checkStyle-gateway-microservice:
  stage: staticAnalysis
  script:
    gradle gateway-microservice:checkstyleMain gateway-microservice:checkStyleTest
  allow_failure: true


PMD-gateway-microservice:
  stage: staticAnalysis
  script:
    gradle gateway-microservice:pmdMain
  allow_failure: true
