image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-messaging-microservice:
  stage: build
  script:
    gradle messaging-microservice:assemble messaging-microservice:testClasses

checkStyle-messaging-microservice:
  stage: staticAnalysis
  script:
    gradle messaging-microservice:checkstyleMain messaging-microservice:checkStyleTest
  allow_failure: true


PMD-messaging-microservice:
  stage: staticAnalysis
  script:
    gradle messaging-microservice:pmdMain
  allow_failure: true

test-messaging-microservice:
  stage: test
  script:
    - gradle messaging-microservice:test messaging-microservice:jacocoTestReport
    - cat messaging-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
